from __future__ import annotations

# Edit this file once, then run the Python files directly.

SINGLE_TRAINING_MIC_ID = 1
ARRAY_MIC_IDS = [1, 2, 3]

SAMPLE_RATE = 44100
GUNSHOT_SAMPLE_DURATION = 2.0
DISTANCE_SAMPLE_DURATION = 1.5

GUNSHOT_SAMPLE_COUNT = 10
AMBIENT_SAMPLE_COUNT = 10
DISTANCE_LABELS_CM = [25, 75]
DISTANCE_SAMPLES_PER_LABEL = 10

LIVE_CAPTURE_DURATION = 2.0
WEB_PORT = 5000
